apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: petclinic-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: petclinic.rules
      rules:
        - alert: PetclinicPodNotRunning
          expr: |
            kube_pod_status_phase{
              namespace="petclinic-helm",
              phase!="Running"
            } == 1
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Petclinic pod is not running"
            description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is in {{ $labels.phase }} state."
