apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-gateway
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - petclinic-helm

  selector:
    matchLabels:
      monitoring: petclinic-gateway

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
